version: '3.8'

services:
  # React 앱 프로덕션 서버
  loop-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loop-dashboard-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - loop-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: loop-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - loop-dashboard
    restart: unless-stopped
    networks:
      - loop-network

  # Let's Encrypt SSL 인증서 자동 갱신
  certbot:
    image: certbot/certbot
    container_name: loop-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

networks:
  loop-network:
    driver: bridge
